name: Simple Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compile gcc project
        uses: rlalik/setup-cpp-compiler@master
        with:
          compiler: latest
      - run: cc main.c
      - name: Create a file xD
        run: touch file.txt
